apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: heketi-pvc-1gig 
 annotations:
   volume.beta.kubernetes.io/storage-class: glusterfs
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1G
