apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: heketi-pvc 
 annotations:
   volume.beta.kubernetes.io/storage-class: glusterfs
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 4Gi
